### ISSUE TITLE
Width issue

### ISSUE THREAD

**Issue by emrecoban** [Jungwoo-An/react-editor-js#234]
### Environment
- @editorjs/editorjs version: 2.27.2
- react-editor-js version: 2.1.0

### Describe
I cannot change the width. I have the same issue: https://github.com/codex-team/editor.js/discussions/1867#discussioncomment-1982754

**Comment by emrecoban** [comment]
This issue seems to be related to Next.js. HMR doesn't work properly, also building.

```css
.ce-block__content,
.ce-toolbar__content {
    max-width: unset !important;
    width: 100%;
}

.cdx-block {
    max-width: unset !important;
    width: 100%;
}
```

#### Update

I've discovered interesting **solution**. Added `@calumk/editorjs-columns` to my project, and then just import.
